###########################################
# Logging configuration
###########################################
logging:

  # path to a file where logs will be saved.
  filename: {{ logfile }}

  # default format for all loggers
  format: '%(message)s'
  file_format: '%(asctime)s [%(levelname)s] [%(name)s] %(message)s'

  # configuring level per logger
  loggers:

    cloudify_agent.api.pm.initd: info

    cloudify_agent.api.utils: info

    cloudify_agent.shell.daemon_factory: info

    cloudify_agent.shell.utils: info
